#ifndef CCHECKIT_H
#define CCHECKIT_H

#include "AEEStdDef.h"

#include "AEEInterface.h"

#if !defined(AEEINTERFACE_CPLUSPLUS)

#include "AEEStdDef.h"

//WARNING: This classID was locally generated by the wizard 12/28/2023
//For commercializing this module, please get a valid ClassID.
#define AEECLSID_CCHECKIT 0x00AC2F58

#else /* C++ */

#include "AEEStdDef.h"

//WARNING: This classID was locally generated by the wizard 12/28/2023
//For commercializing this module, please get a valid ClassID.
const AEECLSID AEECLSID_CCHECKIT = 0x00AC2F58;

#endif /* !defined(AEEINTERFACE_CPLUSPLUS) */

#endif /* #ifndef CCHECKIT_H */
